### ISSUE TITLE
Why not send a pull request to upstream

### ISSUE THREAD

**Issue by mjmacleod** [rshev/SpliXextras#1]
This works fantastically, thank you very much.
I have to wonder though, wouldn't it be great if the main splix package just included this, have you considered sending them a pull request?

**Comment by rshev** [comment]
you're welcome, glad you found it useful.
they have it on sourceforge which apparently has no such thing as pull requests.
and the forums there look pretty dead.
because of that I've decided to put it there.

**Comment by rshev** [comment]
I'll close it until upstream moves somewhere more collaboration-friendly than sourceforge.
Feel free to ping me if that happens.

**Comment by ValdikSS** [comment]
10 years later, it's upstream now: https://github.com/OpenPrinting/splix/
